apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: engine-ingress
  namespace: self-healing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: remediator.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: engine-api
                port:
                  number: 8000
